
# ---------------------------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------------------------

[robot]
d_l = 0.235
d_w = 0.15
r = 0.0475

m_0e = [[1, 0, 0, 0.033],[0, 1, 0, 0],[0, 0, 1, 0.6545],[0, 0, 0, 1]]
b = [[0, 0, 0, 0, 0],[0, -1, -1, -1, 0],[1, 0, 0, 0, 1],[0, -0.5076, -0.3526, -0.2176, 0],[0.033, 0, 0, 0, 0],[0, 0, 0, 0, 0]]
t_b0 = np.array([[1, 0, 0, 0.1662],[0, 1, 0, 0],[0, 0, 1, 0.0026],[0, 0, 0, 1]])

# ---------------------------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------------------------

joint_limits = np.array([[-np.pi/6, np.pi/6],[-3, 0],[-4, 0],[-3, 0],[-np.pi/2, 0]])

[control]
dt = 0.01
k = 1

method = 'screw'
degree = 5

z_standoff = 0.2
pickup_angle = np.pi / 6

shift_x = 0.01
shift_z = 0.02

max_w_dot = 20 #max wheels velocity
max_a_dot = 20 #max arm joints velocity

kp = np.eye(6) * 2
kd = np.eye(6) * 0
ki = np.eye(6) * 0.0005

control_type = 'ff_pi'

test_joint_limits_flag = True

# initial trajectory configuration
tse_init = np.array([[0, 0, 1, 0],[0, 1, 0, 0],[-1, 0, 0, 0.5],[0, 0, 0, 1]])

# cube configurations
tsc_init = np.array([[np.cos(0), -np.sin(0), 0, 1],[np.sin(0), np.cos(0), 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
tsc_final = np.array([[np.cos(-np.pi/2), -np.sin(-np.pi/2), 0, 0],[np.sin(-np.pi/2), np.cos(-np.pi/2), 0, -1],[0, 0, 1, 0.025],[0, 0, 0, 1]])

# chassis_phi, chassis_x, chassis_y, j1, j2, j3, j4, j5, w1, w2, w3, w4
q = np.array([-np.pi/6, -0.2, 0.2, np.pi/2, -np.pi/6, -np.pi/6, 0, 0, 0, 0, 0, 0])

# initial control
u = [0, 0, 0, 0, 0, 0, 0, 0, 0]

# initial gripper state
gripper_state = 0
